name: E2E Tests
on:
  push:
    branches: [ main ]
jobs:
  maestro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash
      - name: Run Maestro Flows
        run: |
          export PATH="$PATH:$HOME/.maestro/bin"
          maestro test .maestro/
